export const AUTHENTICATE_ADMIN = "AUTHENTICATE_ADMIN";
export const AUTHENTICATE_ADMIN_SUCCESS = "AUTHENTICATE_ADMIN_SUCCESS";
export const AUTHENTICATE_ADMIN_FAIL = "AUTHENTICATE_ADMIN_FAIL";
export const LOGOUT = "LOGOUT";
